const shared = {
  title: 'Assembly ERP',
  slug: 'assembly-erp',
  published: true,
  liveUrl: 'https://erp.jisung.lol/',
  repositoryUrl: 'https://github.com/lulupang2/erp_l',
  cover: '/assembly-erp/production.png',
  coverPosition: 'top',
  category: '04 · MANUFACTURING ERP · INVENTORY',
  cardBadge: 'TRANSACTION INTEGRITY',
  stack: ['SvelteKit', 'Go Fiber', 'PostgreSQL', 'sqlc', 'Neon', 'Docker'],
};

export const erpKo = {
  ...shared,
  status: '학습·포트폴리오 프로젝트',
  coverAlt: 'Assembly ERP 실제 데모의 생산 지시 목록과 양품·불량 현황',
  caseStudyLabel: '제작 과정과 상세 보기',
  gallery: {
    tagline: '부품 입고부터 생산·재고 관리까지',
    summary: '제조 업무를 주제로 데이터 정합성과 트랜잭션을 학습했습니다. 부품 입고·부분 생산·불량 처리를 구현하고, 재시도와 동시 요청을 테스트했습니다.',
    image: shared.cover,
    alt: 'Assembly ERP의 생산 지시 목록과 양품·불량 수량',
    caption: '제조 데모 · 생산 지시와 재고 흐름',
    position: 'top right',
  },
  summary: '제조 업무의 데이터 처리를 학습하기 위해 만든 개인 ERP 프로젝트입니다. 품목·BOM·입고·생산·재고 이력을 연결하고, Go 트랜잭션과 멱등 요청으로 중복 제출과 동시 생산을 처리하는 방법을 다뤘습니다.',
  problem: '생산 결과를 기록할 때 부품 소비, 양품·불량 수량과 재고 이력을 어떻게 함께 맞출 수 있을까요? 단일 조직·단일 재고 위치의 데모를 만들고, 이 변경을 하나의 트랜잭션으로 처리하며 중복 제출과 동시 요청을 학습했습니다.',
  screenshots: [{ src: shared.cover, alt: '조립 제조 ERP 생산 지시 화면', caption: '실제 로컬 데모 · 생산 계획과 양품·불량·잔여 수량 조회', width: 1440, height: 1000 }],
  process: [
    { step: '01', title: 'Prototype', description: '품목 → BOM → 입고 → 생산 → 재고 이력의 수직 흐름을 로컬 PostgreSQL로 연결했습니다.', outputs: ['업무 흐름', '로컬 데모'] },
    { step: '02', title: 'Plan', description: '생산 지시와 재고 잠금 순서, 수량 검증, 중복 요청 계약을 정하고 OpenAPI와 ADR로 기록했습니다.', outputs: ['OpenAPI', 'ADR', '잠금 순서'] },
    { step: '03', title: 'Autopilot', description: 'sqlc 생성 쿼리, Goose 마이그레이션과 격리된 DB 통합 테스트로 반복 검증을 구성했습니다.', outputs: ['sqlc', 'Goose', '통합 테스트'] },
    { step: '04', title: 'Review', description: '부분 생산·불량·요청 재시도와 Neon TLS 연결·유휴 복귀를 확인했습니다. 공개 데모를 배포하고 HTTPS 응답도 확인했습니다.', outputs: ['브라우저 검증', 'Neon 검증', '공개 데모'] },
  ],
  highlights: [
    'SvelteKit 업무 화면과 Go Fiber API를 분리하고 명시적 DTO·OpenAPI 계약 사용',
    '생산 지시 잠금 후 UUID 순서로 재고를 잠가 동시 생산의 충돌 처리',
    '생산 실적·집계·재고 잔액·이력·요청 키를 한 트랜잭션으로 커밋',
    '입고·생산 지시·실적 등록의 멱등 키와 요청 해시로 중복 제출 제어',
    '응답 유실 시 원래 입력과 요청 키를 보존해 안전한 재시도 지원',
  ],
  validation: [
    '2026-09-11 기록 기준: 로컬 PostgreSQL 통합 테스트와 브라우저 업무 흐름 검증',
    '전용 Neon DB의 TLS 연결, 마이그레이션, 유휴 후 데이터 유지 확인',
    '단일 조직·단일 재고 위치의 포트폴리오 데모이며 앱 내 인증은 비범위',
    'erp.jisung.lol 공개 배포 완료 · HTTPS 200 응답 확인, 운영 부하 검증과는 구분',
  ],
  detail: { backLabel: 'Portfolio', repositoryLabel: 'GitHub', liveLabel: 'Live Demo', eyebrow: 'PERSONAL PROJECT · MANUFACTURING', problemLabel: '01 · PROBLEM', problemTitle: '생산과 재고를 함께 맞추는 문제', processLabel: '02 · PROCESS', processTitle: '제조 업무로 익힌 트랜잭션과 재시도 처리', buildLabel: '03 · BUILD', buildTitle: '주요 구현', validationLabel: '04 · VALIDATION', validationTitle: '검증과 경계' },
};

export const erpEn = {
  ...shared,
  status: 'PERSONAL LEARNING PROJECT',
  coverAlt: 'Assembly ERP demo production orders with good and defective output quantities',
  caseStudyLabel: 'View case study',
  gallery: {
    tagline: 'From inbound stock to production and inventory',
    summary: 'Used manufacturing workflows to learn data consistency and transactions. Implemented inbound stock, partial production, and defects, then tested retries and concurrent requests.',
    image: shared.cover,
    alt: 'Assembly ERP production orders with good and defective quantities',
    caption: 'Manufacturing demo · Production orders and inventory',
    position: 'top right',
  },
  summary: 'A personal ERP project for learning data handling in manufacturing workflows. I connected items, BOMs, inbound stock, production, and inventory history, using Go transactions and idempotent requests to handle duplicate submissions and concurrent production.',
  problem: 'How can a production update keep component consumption, good and defective quantities, and inventory history consistent? I built a single-organization, single-location demo to learn atomic transactions, duplicate-submission handling, and concurrent requests.',
  screenshots: [{ src: shared.cover, alt: 'Assembly ERP production order screen in Korean', caption: 'Actual local demo · Production plans, good output, defects, and remaining quantities', width: 1440, height: 1000 }],
  process: [
    { step: '01', title: 'Prototype', description: 'Connected items, BOMs, inbound stock, production, and inventory history using local PostgreSQL.', outputs: ['Vertical workflow', 'Local demo'] },
    { step: '02', title: 'Plan', description: 'Defined order and inventory lock ordering, quantity checks, and duplicate-request contracts in OpenAPI and ADRs.', outputs: ['OpenAPI', 'ADRs', 'Lock ordering'] },
    { step: '03', title: 'Autopilot', description: 'Made checks repeatable through sqlc queries, Goose migrations, and isolated database integration tests.', outputs: ['sqlc', 'Goose', 'Integration tests'] },
    { step: '04', title: 'Review', description: 'Verified partial production, defects, retries, Neon TLS, and idle recovery. Deployed the public demo and checked its HTTPS response.', outputs: ['Browser checks', 'Neon checks', 'Public demo'] },
  ],
  highlights: [
    'Separate SvelteKit workflow UI and Go Fiber API with explicit DTOs and OpenAPI contracts',
    'Production-order locks followed by UUID-ordered inventory locks for concurrent operations',
    'Atomic commit of production results, aggregates, balances, ledger entries, and request keys',
    'Idempotency keys and request hashes for inbound stock, orders, and production results',
    'Original input and request key preserved for retry after a lost response',
  ],
  validation: [
    'Recorded September 11, 2026: local PostgreSQL integration and browser workflow checks',
    'Dedicated Neon database verified for TLS, migrations, and data preservation after idle resume',
    'Single-organization, single-location portfolio demo; in-app authentication is out of scope',
    'Public deployment at erp.jisung.lol with HTTPS 200 verified; this is not production load validation',
  ],
  detail: { backLabel: 'Portfolio', repositoryLabel: 'GitHub', liveLabel: 'Live Demo', eyebrow: 'PERSONAL PROJECT · MANUFACTURING', problemLabel: '01 · PROBLEM', problemTitle: 'Keeping production and inventory consistent', processLabel: '02 · PROCESS', processTitle: 'Learning transactions and retries through manufacturing', buildLabel: '03 · BUILD', buildTitle: 'Key implementation', validationLabel: '04 · VALIDATION', validationTitle: 'Validation and boundaries' },
};
