const shared = {
  title: 'GrantFit',
  slug: 'grantfit',
  published: true,
  cover: '/grantfit/architecture.svg',
  coverPosition: 'top',
  category: '07 · AI & SEARCH · MICROSERVICES',
  cardBadge: 'DETERMINISTIC SEARCH',
  stack: ['Next.js', 'FastAPI', 'PostgreSQL', 'GIN FTS', 'TokenRouter (Kimi K3)', 'Nx', 'Docker Compose'],
};

export const grantfitKo = {
  ...shared,
  status: '학습·포트폴리오 프로젝트 · 마이크로서비스 설계',
  coverAlt: 'GrantFit 마이크로서비스 및 데이터 격리 아키텍처 다이어그램',
  caseStudyLabel: '제작 과정과 상세 보기',
  gallery: {
    tagline: '정부지원사업 적합도 판정 및 비침투적 AI 검색',
    summary: '기업 프로필과 공고 요건을 결정론적 도메인 규칙으로 비교하여 적합도와 판정 근거를 산출하고, Kimi K3 기반 요약을 비침투적으로 연동한 검색 플랫폼입니다.',
    image: shared.cover,
    alt: 'GrantFit 시스템 아키텍처 다이어그램',
    caption: '시스템 설계도 · Web/BFF 및 Catalog/Discovery 마이크로서비스 구조',
    position: 'top',
  },
  summary: '중소·벤처기업 프로필(소재지, 업력, 업종, 성장단계, 인증 등)과 정부지원사업 공고의 자격 요건을 정밀 대조하여 추천·확인 필요·불일치 판정과 명확한 근거를 제공하는 검색 서비스입니다. Next.js Web/BFF, 2개의 FastAPI 마이크로서비스(Catalog, Discovery), 서비스별 전용 PostgreSQL 컨테이너를 모노레포로 구축했습니다.',
  problem: '정부지원사업 공고는 주관 기관마다 양식이 제각각이고 지원 자격 조건(지역, 업력, 필수 인증, 마감일)이 복잡하게 얽혀 있어 기업이 적합성을 직접 판단하기 어렵습니다. 또한 무분별하게 LLM만을 앞세운 검색 방식은 환각(Hallucination), 비결정성, 외부 API 장애 및 비용 문제를 유발하며 판정의 신뢰도를 저해합니다.',
  role: {
    summary: 'Nx 기반 모노레포 구조 설계부터 풀스택 마이크로서비스 아키텍처, 규칙 기반 자격 판정 알고리즘, LLM 폴백 파이프라인까지 전 과정을 1인 설계·구현했습니다.',
    items: [
      'Nx + pnpm + uv 하이브리드 모노레포 구축 및 shared contracts 타입 정의',
      'Next.js 기반 Web/BFF 라우트 및 반응형 검색 인터페이스 개발',
      'FastAPI 기반 Catalog 및 Discovery 마이크로서비스 독립 서비스 구축 및 DB 모델링',
      'PostgreSQL GIN Full-Text Search 및 도메인 규칙 기반 결정론적 랭킹/판정 엔진(ranking.py) 개발',
      'TokenRouter API(Kimi K3) 비침투적 요약 레이어 및 실패 시 결정론적 템플릿 폴백 파이프라인(answering.py) 구현',
    ],
  },
  screenshots: [
    {
      src: '/grantfit/architecture.svg',
      alt: 'GrantFit 마이크로서비스 및 데이터 격리 아키텍처 다이어그램',
      caption: '설계 다이어그램 (소스코드 기반 아키텍처 도면, UI 캡처 아님) · Web/BFF, Catalog, Discovery 서비스 및 DB 격리 구조',
      width: 1200,
      height: 800,
    },
    {
      src: '/grantfit/search-flow.svg',
      alt: 'GrantFit 검색 및 자격 판정 파이프라인 다이어그램',
      caption: '엔진 파이프라인 다이어그램 (UI 캡처 아님) · FTS 후보 추출, 결정론적 규칙 평가, 비침투적 LLM 요약 및 폴백 흐름',
      width: 1200,
      height: 800,
    },
  ],
  process: [
    {
      step: '01',
      title: 'Prototype',
      description: '정부지원사업 자격 요건 판정에서 LLM의 환각 위험을 배제하기 위해 결정론적 규칙 평가를 SSOT로 정립하는 ADR-0004를 수립했습니다. PostgreSQL 전문 검색(FTS)과 기업 프로필(지역, 업력, 업종) 비교를 통한 최소 판정 프로토타입을 검증했습니다.',
      outputs: ['ADR-0004 수립', '규칙 기반 판정 프로토타입', 'FTS 인덱스 검증'],
    },
    {
      step: '02',
      title: 'Plan',
      description: 'Nx 모노레포 환경에서 pnpm(Web/BFF)과 uv(독립 Python 마이크로서비스)를 분리하는 하이브리드 아키텍처(ADR-0007)를 설계했습니다. Catalog DB(원본 공고)와 Discovery DB(검색 프로젝션)를 물리 컨테이너 수준에서 완전 분리했습니다.',
      outputs: ['ADR-0007 모노레포 구조', '서비스별 DB 스키마', 'shared contracts 정의'],
    },
    {
      step: '03',
      title: 'Autopilot',
      description: 'Discovery가 Catalog의 내부 엔드포인트(/internal/v1/*)를 주기적으로 폴링하는 Pull 기반 비동기 프로젝션(ADR-0003)을 구현했습니다. TokenRouter Kimi K3 연동 시 프롬프트 인젝션을 방어하고, 외부 API 오류 발생 시 결정론적 요약으로 즉시 폴백하도록 구축했습니다.',
      outputs: ['Pull 동기화 엔진', 'TokenRouter 연동', '비침투적 요약 파이프라인'],
    },
    {
      step: '04',
      title: 'Review',
      description: 'Docker Compose 환경에서 Catalog 장애 시뮬레이션 및 LLM 타임아웃 테스트를 수행했습니다. 외부 AI 장애나 API 키 누락 상황에서도 검색 API가 HTTP 200과 결정론적 요약을 일관되게 반환함을 확인하고, 단일 EC2 인프라 토폴로지의 경계를 정리했습니다.',
      outputs: ['장애 격리 검증', '결정론적 폴백 테스트', '인프라 경계 명세'],
    },
  ],
  decisions: [
    {
      title: 'ADR-0004: 결정론적 규칙 기반 자격 판정 우선',
      context: 'LLM에 자격 판정이나 적합도 점수 계산을 위임할 경우 환각 현상, 비결정성, 외부 API 지연이 검색 신뢰도를 훼손합니다.',
      decision: 'LLM이 점수나 판정을 변경하지 못하도록 제한하고, 재현 가능한 Python 규칙 엔진과 PostgreSQL FTS를 검색 품질의 단일 진실 공급원(SSOT)으로 확립했습니다.',
      impact: '판정 결과와 근거가 외부 AI의 응답에 좌우되지 않도록 분리했습니다.',
    },
    {
      title: 'ADR-0008: 비침투적 LLM 요약 및 프롬프트 인젝션 차단',
      context: '사용자 검색어에 시스템 프롬프트 탈취나 우회 시도가 포함될 위험이 있으며, 불필요한 LLM 호출은 비용을 가중시킵니다.',
      decision: '명시적 요약 요청(generateAnswer=true) 시에만 상위 3개 공고에 한해 Kimi K3를 호출하며, 사용자 원문 질의어를 모델 입력에서 완전히 배제하고 정제된 공고 JSON만 공급했습니다.',
      impact: '프롬프트 인젝션 위험을 낮추고 불필요한 LLM API 토큰 사용을 제한했습니다.',
    },
    {
      title: 'ADR-0003: Pull 기반 카탈로그 프로젝션 비동기 동기화',
      context: '검색 조회(hot-path)가 원본 공고 관리 서비스(Catalog)의 가용성에 직접 결합되면 공고 등록/수정 시 검색 장애가 전파됩니다.',
      decision: 'Discovery 서비스가 Catalog 내부 API(/internal/v1/*)를 주기적으로 폴링하여 자체 PostgreSQL FTS 인덱스에 비동기 프로젝션하도록 설계했습니다.',
      impact: 'Catalog 서비스가 일시 중단되거나 배포 중이더라도 Discovery의 검색 가용성을 독립적으로 유지할 수 있습니다.',
    },
    {
      title: 'ADR-0007: Nx + pnpm + uv 독립 런타임 분리',
      context: 'Node.js 기반 Next.js와 Python 기반 FastAPI 마이크로서비스를 단일 패키지 매니저로 묶으면 가상환경 오염과 의존성 충돌이 발생합니다.',
      decision: 'pnpm은 Web과 shared contracts만 관리하고, Catalog와 Discovery는 각각 전용 pyproject.toml과 uv.lock을 갖도록 분리한 뒤 Nx가 빌드 및 테스트를 오케스트레이션하도록 구성했습니다.',
      impact: '각 서비스의 런타임 격리와 재현 가능한 빌드 환경을 구축하고 의존성 격리를 달성했습니다.',
    },
  ],
  troubleshooting: [
    {
      title: '외부 LLM API 지연 및 실패 시 검색 중단 위험',
      problem: 'Kimi K3 모델 응답 지연이나 토큰 한도 초과, 네트워크 타임아웃 발생 시 전체 검색 요청이 실패할 위험 존재.',
      cause: '검색 결과와 요약 생성이 단일 호출 체인으로 묶여 외부 서비스 장애가 전체 API 실패로 전파됨.',
      solution: 'LLM 호출에 제한 시간과 동시 실행 제한을 두고 AI 요청 실패 시 기존 규칙 기반 요약을 유지하도록 구현했습니다. 검색 경로의 다른 장애까지 HTTP 200으로 처리한다는 뜻은 아닙니다.',
    },
    {
      title: '공고 데이터 변경 시 검색 인덱스와의 정합성 지연 및 누락',
      problem: '비동기 폴링 환경에서 네트워크 패킷 유실이나 Catalog 재시작 시 특정 공고 변경 사항이 Discovery 인덱스에 누락될 위험.',
      cause: '단순 타임스탬프 기반 폴링은 동시 수정이나 시계 드리프트 시 변경 건을 놓칠 수 있음.',
      solution: '단조 증가하는 revision 번호 기반 change feed를 구축하고, revision 불일치나 sequence gap 감지 시 snapshot 교체 모드로 자동 전환하여 인덱스 정합성을 안전하게 복구함.',
    },
    {
      title: '사용자 임의 질의어를 통한 프롬프트 인젝션 무력화 시도',
      problem: '공고 검색창에 프롬프트 탈취 악의적 문장을 입력했을 때 LLM 요약문이 오염될 위험.',
      cause: '사용자 자유 텍스트가 시스템 프롬프트 컨텍스트에 직접 결합될 경우 프롬프트 오버라이드 취약점이 발생함.',
      solution: 'LLM에 전달되는 프롬프트에서 사용자 원문 검색어, 요청 ID, 외부 URL을 완전히 배제하고 서버가 사전 검증한 공고의 제목과 판정 메타데이터 JSON만 프롬프트에 주입함.',
    },
  ],
  highlights: [
    'Nx + pnpm + uv 하이브리드 모노레포 기반 Next.js Web/BFF 및 2개 FastAPI 마이크로서비스 구축',
    'PostgreSQL 전용 컨테이너 2기를 통한 Catalog 및 Discovery 서비스 간 물리적 DB 소유권 격리',
    'PostgreSQL GIN FTS와 도메인 규칙 기반 결정론적 지원 자격 판정 엔진(ranking.py) 구현',
    'TokenRouter Kimi K3 비침투적 요약 레이어 및 장애 시 결정론적 템플릿 폴백 파이프라인(answering.py) 연동',
    '단조 증가 revision 기반 change feed를 활용한 Pull 방식의 비동기 검색 프로젝션 동기화',
  ],
  validation: [
    'Docker Compose 기반 전체 스택 로컬 오케스트레이션 검증 완료 (Node.js test runner 및 pytest 검증)',
    '외부 AI 장애 시뮬레이션 환경에서 결정론적 템플릿 폴백 및 HTTP 200 정상 반환 검증 완료',
    '별도의 공용 Git 원격 저장소나 상용 라이브 배포 URL은 없으며 로컬 모노레포 환경으로 검증 완료',
    '단일 호스트 Docker Compose 토폴로지 기준이며 다중 인스턴스 부하분산이나 HA는 미구현',
  ],
  outcome: {
    summary: '결정론적 자격 판정과 선택적 AI 요약을 분리하고, 서비스별 데이터 소유권을 둔 검색 구조를 구현했습니다.',
    results: [
      '외부 AI 응답과 분리된 재현 가능한 규칙 기반 자격 판정 체계 구축',
      '서비스별 DB와 명시적 contracts 패키지를 통한 마이크로서비스 경계 구성',
      'LLM 오류 시 결정론적 요약으로 폴백하는 검색 경로 구성',
    ],
    learnings: [
      'LLM을 비즈니스 로직 판정이 아닌 보조적 요약 레이어로 격리하는 것이 엔지니어링 신뢰성의 핵심임을 체득',
      '마이크로서비스 간 DB 공유를 배제하고 Pull 기반 비동기 프로젝션을 채택하여 장애 전파를 차단하는 패턴 학습',
      '복잡한 자연어 의미 검색을 위해서는 추후 고밀도 벡터 임베딩(Vector Search) 도입이 필요함을 인지',
    ],
  },
  detail: {
    backLabel: 'Portfolio',
    eyebrow: 'PERSONAL PROJECT · AI & MICROSERVICES',
    problemLabel: '01 · PROBLEM',
    problemTitle: '복잡한 지원 자격과 LLM 비결정성의 한계',
    roleLabel: '02 · ROLE & SCOPE',
    roleTitle: '마이크로서비스 및 판정 엔진 1인 설계·구현',
    processLabel: '03 · PROCESS',
    processTitle: '모노레포 구축부터 결정론적 폴백 파이프라인까지',
    decisionsLabel: '04 · TECHNICAL DECISIONS',
    decisionsTitle: '신뢰성 있는 검색을 위한 아키텍처 의사결정',
    troubleshootingLabel: '05 · TROUBLESHOOTING',
    troubleshootingTitle: 'AI 장애 격리 및 인덱스 정합성 유지',
    buildLabel: '06 · BUILD',
    buildTitle: '주요 구현',
    validationLabel: '07 · VALIDATION',
    validationTitle: '검증 기록과 시스템 경계',
    outcomeLabel: '08 · RESULTS & RETROSPECTIVE',
    outcomeTitle: '프로젝트 성과와 배운 점',
  },
};

export const grantfitEn = {
  ...shared,
  status: 'PERSONAL PROJECT · MICROSERVICES ARCHITECTURE',
  coverAlt: 'GrantFit microservices and data isolation architecture diagram',
  caseStudyLabel: 'View case study',
  gallery: {
    tagline: 'Government grant qualification and non-invasive AI search',
    summary: 'Built a search engine comparing business profiles with grant requirements using deterministic domain rules, integrating non-invasive Kimi K3 summaries with fallback resilience.',
    image: shared.cover,
    alt: 'GrantFit system architecture diagram',
    caption: 'System architecture diagram · Web/BFF and Catalog/Discovery microservice topology',
    position: 'top',
  },
  summary: 'A search engine that compares small business profiles (location, company age, sector, growth stage, certifications) with government grant criteria, providing match verdicts, review flags, and explicit evidence. Built as a monorepo comprising a Next.js Web/BFF, two FastAPI microservices (Catalog, Discovery), and dedicated PostgreSQL database containers.',
  problem: 'Government grant announcements lack uniform formatting, and intricate eligibility constraints (region, company age, mandatory certifications, deadlines) make manual qualification tedious. Furthermore, naive LLM-first search introduces hallucinations, non-determinism, external API dependencies, and high token costs, degrading decision confidence.',
  role: {
    summary: 'Designed and implemented the full-stack architecture, Nx monorepo orchestration, deterministic Python rule engine, and resilient LLM fallback pipelines as a solo engineer.',
    items: [
      'Architected Nx + pnpm + uv hybrid monorepo with typed contract packages',
      'Developed Next.js Web/BFF route handlers and responsive search interface',
      'Implemented FastAPI Catalog and Discovery microservices with dedicated PostgreSQL containers',
      'Engineered PostgreSQL GIN Full-Text Search and deterministic qualification rule engine (ranking.py)',
      'Built TokenRouter Kimi K3 non-invasive summarizer with instant deterministic template fallback (answering.py)',
    ],
  },
  screenshots: [
    {
      src: '/grantfit/architecture.svg',
      alt: 'GrantFit microservices and data isolation architecture diagram',
      caption: 'System architecture diagram (source-backed diagram, not a live UI screenshot) · Web/BFF, Catalog, Discovery services with isolated databases',
      width: 1200,
      height: 800,
    },
    {
      src: '/grantfit/search-flow.svg',
      alt: 'GrantFit search and qualification pipeline diagram',
      caption: 'Pipeline diagram (not a live UI screenshot) · FTS candidate retrieval, deterministic rule engine, and non-invasive LLM fallback',
      width: 1200,
      height: 800,
    },
  ],
  process: [
    {
      step: '01',
      title: 'Prototype',
      description: 'Formalized ADR-0004 to establish deterministic domain rules as the single source of truth for qualification verdicts, eliminating LLM hallucination risks. Verified an initial prototype combining PostgreSQL Full-Text Search with corporate profile criteria checks.',
      outputs: ['ADR-0004 decision record', 'Rule engine prototype', 'FTS index validation'],
    },
    {
      step: '02',
      title: 'Plan',
      description: 'Designed a hybrid monorepo separating pnpm (Web/BFF) from uv (independent Python microservices) under ADR-0007. Established complete container-level isolation between Catalog DB (origin announcements) and Discovery DB (search read projection).',
      outputs: ['ADR-0007 monorepo design', 'Isolated database schemas', 'Shared contract definitions'],
    },
    {
      step: '03',
      title: 'Autopilot',
      description: 'Implemented pull-based asynchronous projection (ADR-0003), where Discovery periodically polls Catalog internal endpoints (/internal/v1/*). Connected TokenRouter Kimi K3 with prompt injection shields and automated fallback to deterministic templates upon API failure.',
      outputs: ['Pull sync engine', 'TokenRouter client', 'Non-invasive summary pipeline'],
    },
    {
      step: '04',
      title: 'Review',
      description: 'Executed simulated Catalog downtime and LLM latency tests inside Docker Compose. Verified that the search API consistently returns HTTP 200 with deterministic summaries during external AI outages, documenting single-instance host deployment boundaries.',
      outputs: ['Failure isolation checks', 'Deterministic fallback tests', 'Infrastructure boundary spec'],
    },
  ],
  decisions: [
    {
      title: 'ADR-0004: Prioritizing Deterministic Qualification Rules',
      context: 'Delegating eligibility evaluation to an LLM introduces hallucinations, non-deterministic scores, and severe latency during search queries.',
      decision: 'Barred the LLM from computing scores or verdicts, establishing reproducible Python domain rules and PostgreSQL FTS as the sole qualification SSOT.',
      impact: 'Kept qualification verdicts and evidence independent of external AI response content.',
    },
    {
      title: 'ADR-0008: Non-Invasive LLM Summary with Injection Defense',
      context: 'User search inputs can contain prompt injection attacks, and invoking LLMs on every query inflates token expenses.',
      decision: 'Invoked Kimi K3 only on explicit user request (generateAnswer=true) for top 3 ranked grants, strictly excluding raw user search queries from LLM prompts.',
      impact: 'Reduced prompt injection exposure and limited unnecessary LLM API usage.',
    },
    {
      title: 'ADR-0003: Pull-Based Asynchronous Catalog Index Projection',
      context: 'Coupling the search read path directly to Catalog service availability risks cascading outages whenever Catalog undergoes maintenance.',
      decision: 'Configured Discovery to poll Catalog internal endpoints periodically, building its own denormalized PostgreSQL FTS projection asynchronously.',
      impact: 'Allowed the Discovery search projection to remain available during temporary Catalog interruptions.',
    },
    {
      title: 'ADR-0007: Nx + pnpm + uv Independent Runtime Separation',
      context: 'Bundling Node.js and multiple Python microservices into a single dependency manager causes environment pollution and version conflicts.',
      decision: 'Scoped pnpm to Web and shared contracts, gave each Python microservice its own pyproject.toml and uv.lock, and orchestrated tasks via Nx.',
      impact: 'Ensured clean runtime isolation, frozen lockfiles, and reliable local reproduction across heterogeneous stacks.',
    },
  ],
  troubleshooting: [
    {
      title: 'Mitigating Search Outages from External LLM Failures',
      problem: 'Spikes in Kimi K3 response latency, quota depletion, or network timeouts threatened to fail the entire user search request.',
      cause: 'Coupling search result retrieval and AI summarization into a single sequential block allowed downstream failures to abort the parent request.',
      solution: 'Wrapped LLM calls in Discovery with a 30-second timeout and concurrency semaphore, triggering instant fallback to deterministic template summaries returning HTTP 200 and mode="deterministic".',
    },
    {
      title: 'Preventing Index Drift during Catalog Revisions',
      problem: 'Packet drops or Catalog restarts during asynchronous polling could cause missed announcement updates in the Discovery FTS index.',
      cause: 'Timestamp-based polling suffers from clock drift and missed updates during concurrent revision writes.',
      solution: 'Implemented a monotonically increasing revision change feed in Catalog; Discovery detects sequence gaps and automatically triggers a full snapshot replacement.',
    },
    {
      title: 'Shielding Against Prompt Injection in User Search Queries',
      problem: 'Adversarial inputs in the search box attempted to override system prompts or exfiltrate internal system instructions.',
      cause: 'Directly concatenating untrusted user queries into LLM prompts introduces prompt injection vulnerabilities.',
      solution: 'Excluded raw user queries, request IDs, and source URLs from LLM prompts, supplying only sanitized structured grant JSON attributes.',
    },
  ],
  highlights: [
    'Next.js Web/BFF and two FastAPI microservices orchestrated via an Nx + pnpm + uv hybrid monorepo',
    'Physical database isolation between Catalog and Discovery using dedicated PostgreSQL containers',
    'Deterministic grant qualification engine and PostgreSQL GIN Full-Text Search index (ranking.py)',
    'Non-invasive TokenRouter Kimi K3 summarizer with instant deterministic template fallback (answering.py)',
    'Monotonic revision change feed driving pull-based asynchronous search index projections',
  ],
  validation: [
    'Entire stack verified under local Docker Compose with Node.js test runner and pytest suites passing',
    'Demonstrated resilient deterministic fallback and reliable HTTP 200 responses during simulated AI outages',
    'No public Git remote or hosted live deployment exists; verified strictly in local monorepo environment',
    'Operates as a single-host Docker Compose deployment; multi-instance load balancing and HA are future scope',
  ],
  outcome: {
    summary: 'Built a microservice search architecture separating deterministic qualification rules from AI summaries and isolating service responsibilities.',
    results: [
      'Established a reproducible qualification baseline independent of external AI response content',
      'Enforced microservice data boundaries with dedicated databases and shared typed contracts',
      'Added deterministic summary fallback when LLM requests fail',
    ],
    learnings: [
      'Confirmed that confining LLMs to non-invasive summary roles is vital for engineering reliability in decision systems',
      'Learned the effectiveness of pull-based asynchronous projections for preventing cross-service cascading failures',
      'Recognized that complex semantic queries will benefit from dense vector embedding pipelines as a future phase',
    ],
  },
  detail: {
    backLabel: 'Portfolio',
    eyebrow: 'PERSONAL PROJECT · AI & MICROSERVICES',
    problemLabel: '01 · PROBLEM',
    problemTitle: 'Intricate Eligibility Rules and LLM Non-Determinism',
    roleLabel: '02 · ROLE & SCOPE',
    roleTitle: 'Full-Stack Microservices Architecture & Rule Engine',
    processLabel: '03 · PROCESS',
    processTitle: 'From Monorepo Setup to Resilient Fallback Pipelines',
    decisionsLabel: '04 · TECHNICAL DECISIONS',
    decisionsTitle: 'Architectural Decisions for Reliable Search',
    troubleshootingLabel: '05 · TROUBLESHOOTING',
    troubleshootingTitle: 'AI Fault Isolation and Index Consistency',
    buildLabel: '06 · BUILD',
    buildTitle: 'Key Implementation',
    validationLabel: '07 · VALIDATION',
    validationTitle: 'Verification Evidence and System Boundaries',
    outcomeLabel: '08 · RESULTS & RETROSPECTIVE',
    outcomeTitle: 'Project Outcomes and Retrospective',
  },
};
