const shared = {
  title: 'PricePulse',
  slug: 'pricepulse',
  published: true,
  cover: '/pricepulse/dashboard.webp',
  coverPosition: 'top',
  category: '06 · AUTOMATION · CRAWLER & WORKFLOW',
  cardBadge: 'AUTOMATION & MONITORING',
  stack: ['Next.js', 'FastAPI', 'Playwright', 'PostgreSQL', 'MinIO', 'n8n', 'Docker Compose'],
};

export const pricepulseKo = {
  ...shared,
  status: '학습·포트폴리오 프로젝트 · 로컬 Docker 검증',
  coverAlt: 'PricePulse 가격 관측 대시보드 화면',
  caseStudyLabel: '제작 과정과 상세 보기',
  gallery: {
    tagline: '스마트스토어 가격 모니터링과 이상 탐지',
    summary: '가격·재고 변동을 기록하고 알림으로 전달하는 수집 경로를 구현했습니다. 로컬 검증 네트워크의 로그인 리다이렉트로 실제 상품 수집과 Slack 전송은 끝까지 확인하지 못했습니다.',
    image: shared.cover,
    alt: 'PricePulse 가격 모니터링 대시보드',
    caption: '관제 대시보드 · 모니터링 대상 상품 목록과 수집 상태',
    position: 'top',
  },
  summary: '네이버 스마트스토어 상품의 가격·재고 변동을 관측하기 위해 만든 개인 프로젝트입니다. Playwright 수집기, FastAPI API, PostgreSQL 이력, n8n 알림 흐름과 Next.js 대시보드를 Docker Compose로 구성했습니다. 실제 상품 수집과 Slack 발송의 종단 간 검증은 네트워크 접근 제한으로 남아 있습니다.',
  problem: '다른 판매자의 상품은 판매자 전용 Commerce API로 조회할 수 없어 공개 페이지를 수집하는 경로를 선택했습니다. 로그인 리다이렉트와 차단이 발생하는 환경에서는 가격을 얻지 못하므로, 수집 실패를 성공한 관측값처럼 저장하지 않는 것도 필요했습니다.',
  role: {
    summary: '모노레포 설계부터 크롤링 파이프라인, 비동기 백엔드 API, n8n 워크플로, 컨테이너 인프라까지 전 과정을 1인 개발로 수행했습니다.',
    items: [
      'Turborepo 기반 모노레포 구축 (Next.js 웹, FastAPI 백엔드, n8n 워크플로, Compose 인프라)',
      'Playwright 기반 브라우저 풀 관리 및 JSON-LD / __NEXT_DATA__ 우선 파싱 엔진 구현',
      'FastAPI 비동기 API 서버, SQLAlchemy 2.0 ORM 모델링(9개 테이블), 내부 보호 엔드포인트 구축',
      'Argon2id 세션 인증, SHA-256 토큰 단방향 해싱, IP 기반 Rate Limit 보안 체계 수립',
      'n8n 스케줄 트리거 기반 이벤트 적재, Slack 웹훅 발송, MinIO 오류 아티팩트 보관 파이프라인 연계',
    ],
  },
  screenshots: [
    {
      src: '/pricepulse/dashboard.webp',
      alt: 'PricePulse 가격 관측 대시보드 화면',
      caption: '실제 로컬 데모 · 등록 상품 목록, 수집 상태, 최근 변동 요약 대시보드',
      width: 1440,
      height: 900,
    },
    {
      src: '/pricepulse/product-detail.webp',
      alt: '상품 상세 및 가격 이력 차트 화면',
      caption: '실제 로컬 데모 · 상품별 최저가/할인가 추이 SVG 차트 및 수집 로그',
      width: 1440,
      height: 900,
    },
    {
      src: '/pricepulse/admin-login.webp',
      alt: '관리자 세션 로그인 화면',
      caption: '실제 로컬 데모 · Argon2id 및 HttpOnly 쿠키 기반 관리자 인증 화면',
      width: 1440,
      height: 900,
    },
  ],
  process: [
    {
      step: '01',
      title: 'Prototype',
      description: '네이버 커머스 공식 API의 다중 스토어 관측 한계를 분석하고, 헤드리스 Chromium 기반 Playwright 크롤링으로 전환하는 ADR-0002를 수립했습니다. 단일 상품 URL에서 기본 가격과 품절 여부를 추출하는 최소 수집 프로토타입을 검증했습니다.',
      outputs: ['ADR-0002 의사결정', 'Playwright 수집 검증', '최소 파서 프로토타입'],
    },
    {
      step: '02',
      title: 'Plan',
      description: '자주 변경되는 프론트엔드 DOM 셀렉터 대신 스마트스토어의 표준 구조화 데이터인 JSON-LD와 SSR 상태 객체(__NEXT_DATA__)를 우선 탐색하는 3단계 파싱 전략을 설계했습니다. 비동기 수집 루프와 알림 발송 책임을 분리하는 데이터 모델을 수립했습니다.',
      outputs: ['3단계 파싱 명세', '9개 테이블 스키마', '수집·알림 분리 모델'],
    },
    {
      step: '03',
      title: 'Autopilot',
      description: 'FastAPI 비동기 엔드포인트와 SQLAlchemy 2.0을 구성하고 n8n 워크플로 스케줄러를 연결했습니다. 요청 간 무작위 지연(jitter)과 브라우저 무쿠키 격리 실행을 적용하고, 네이버 로그인 페이지 리다이렉트 발생 시 NAVER_AUTH_FAILED 예외로 즉시 분류하도록 자동화했습니다.',
      outputs: ['FastAPI 백엔드', 'n8n 워크플로', '스텔스 크롤러 엔진'],
    },
    {
      step: '04',
      title: 'Review',
      description: '저장소의 로컬 검증 기록에는 백엔드 단위 테스트 42개와 통합 테스트 18개가 남아 있습니다. 검증 네트워크의 네이버 로그인 리다이렉트 때문에 실제 상품 파싱과 Slack 발송까지는 확인하지 못했습니다.',
      outputs: ['단위/통합 60개 테스트', '차단 감지 검증', '운영 한계점 분석'],
    },
  ],
  decisions: [
    {
      title: 'ADR-0002: 헤드리스 브라우저 직접 수집 채택',
      context: '공식 Naver Commerce API는 본인 스토어 자격증명만 허용하여 경쟁사 가격 비교가 불가능했고, 쇼핑 검색 API는 서비스가 종료되었습니다.',
      decision: '판매자 전용 API 대신 Playwright 수집기를 구현하고, 접근이 차단된 응답은 실패 상태로 분류했습니다.',
      impact: '대상 상품 페이지에 접근할 수 있는 환경에서는 관측을 시도할 수 있지만, 차단된 환경에서의 수집 성공은 보장하지 않습니다.',
    },
    {
      title: 'JSON-LD 및 __NEXT_DATA__ 우선 추출 전략',
      context: '이커머스 웹페이지의 DOM 트리와 CSS 클래스명은 잦은 UI 개편으로 인해 쉽게 깨지고 유지보수 비용이 급증합니다.',
      decision: '구현된 파서는 JSON-LD와 __NEXT_DATA__를 순서대로 검사합니다. DOM fallback은 아직 구현되지 않았습니다.',
      impact: '구조화 데이터가 없는 페이지는 읽지 못하며, 실제 사이트 변경에 대한 복원력은 추가 검증이 필요합니다.',
    },
    {
      title: 'FastAPI 수집과 n8n 알림 분산 큐 격리',
      context: '크롤링 루프 내부에서 외부 Slack 웹훅을 직접 동기 호출할 경우 네트워크 지연이나 외부 장애가 수집 전체 트랜잭션을 지연시킵니다.',
      decision: 'FastAPI는 가격 변동 이벤트를 DB(alert_events)에 추가만 하고, n8n 워크플로가 주기적으로 대기 이벤트를 폴링·발송·확인하는 비동기 분산 큐 구조로 분리했습니다.',
      impact: '비동기 알림 처리로 외부 알림 서비스의 지연이 크롤링 수집 주기에 전파되지 않도록 설계했습니다.',
    },
  ],
  troubleshooting: [
    {
      title: 'Docker Compose 내 Argon2id 해시 특수문자($) 치환 손상',
      problem: 'Docker Compose 환경에서 관리자 계정 생성 시 Argon2id 해시 문자열($argon2id$v=19$...) 내부의 $ 기호가 환경변수 문법으로 오인 치환되어 로그인이 실패함.',
      cause: 'Docker Compose 명세상 환경변수 내 달러 기호($)는 치환 연산자로 인식되어 값이 누락되거나 왜곡됨.',
      solution: 'compose.yaml 및 .env.example에 $$argon2id$$... 형태로 달러 기호를 명시적으로 이스케이프 처리하여 해시 무결성을 보장함.',
    },
    {
      title: '루트 실행 컨텍스트 차이에 따른 환경변수 누락',
      problem: '루트 디렉터리에서 Compose 실행 시 infra/ 경로의 환경변수가 주입되지 않아 컨테이너 간 DB 연결 정보 누락 발생.',
      cause: 'docker compose -f infra/compose.yaml 호출 시 compose 파일이 위치한 서브디렉터리를 기준으로 .env를 탐색함.',
      solution: '루트 package.json의 실행 스크립트에 --env-file .env 옵션을 명시하여 실행 위치와 무관하게 일관된 설정을 주입하도록 수정함.',
    },
    {
      title: '네이버 봇 차단 탐지 및 상태 분류 오류',
      problem: '네이버 스마트스토어 요청 시 봇 탐지로 로그인 페이지 리다이렉트가 발생했을 때 일반 파싱 에러로 잘못 처리되어 무한 재시도가 일어남.',
      cause: '리다이렉트 최종 목적지 URL(nid.naver.com) 검증 누락으로 비정상 응답을 일반 HTML 파싱 실패로 취급함.',
      solution: '응답 URL을 검사하여 로그인 리다이렉트 감지 시 재시도 불가능한 NAVER_AUTH_FAILED 예외로 즉시 승격하고 수집 실패 로그를 명확히 기록함.',
    },
  ],
  highlights: [
    'Next.js 16 대시보드와 FastAPI 비동기 API 서버를 Turborepo 모노레포로 구성',
    'Playwright Chromium 스텔스 모드 및 JSON-LD / __NEXT_DATA__ 2단계 구조화 데이터 파서 구축',
    'FastAPI 내부 토큰 보호 엔드포인트(/internal/v1/*)와 n8n 스케줄 트리거 연동',
    'PostgreSQL 16 기반 9개 테이블 비동기 ORM 모델링 및 Alembic 마이그레이션 관리',
    'Argon2id 비밀번호 해싱 및 SHA-256 CSRF 토큰 기반 세션 보안 체계 구축',
  ],
  validation: [
    '로컬 Docker Compose 환경 검증 완료 · 백엔드 단위 42개 및 통합 18개 테스트 통과',
    '로컬 검증 네트워크상 네이버 로그인 리다이렉트로 실데이터 수집/Slack E2E는 제한되었으며 차단 감지 경로만 검증됨',
    '3단계 파싱 전략 중 DOM fallback 파서는 미구현 상태이며 JSON-LD/__NEXT_DATA__ 우선 추출로 동작',
    '공식 라이브 도메인 배포는 없으며 로컬 Docker Compose 인프라 템플릿 형태로 검증 완료',
  ],
  outcome: {
    summary: '가격 이력과 알림을 분리한 로컬 모니터링 흐름을 구현했습니다. 실제 상품 수집과 Slack 전달은 검증 네트워크에서 완료하지 못했습니다.',
    results: [
      'Docker Compose 로컬 구성에서 기록된 백엔드 단위 테스트 42개와 통합 테스트 18개 확인',
      '네이버 로그인 리다이렉트 즉시 감지 및 에러 격리를 통한 비정상 재시도 루프 차단',
    ],
    learnings: [
      '수집기 코드만으로 외부 사이트 접근을 보장할 수 없으므로 네트워크 차단과 이용 조건을 먼저 확인해야 함을 배웠습니다.',
      '구조화 데이터가 없는 페이지에는 별도의 파싱 전략과 검증이 필요합니다.',
      '크롤링 수집과 알림 발송 책임을 DB 큐를 통해 분리하는 비동기 아키텍처의 중요성 체득',
    ],
  },
  detail: {
    backLabel: 'Portfolio',
    repositoryLabel: 'GitHub',
    eyebrow: 'PERSONAL PROJECT · AUTOMATION & CRAWLER',
    problemLabel: '01 · PROBLEM',
    problemTitle: '공식 API 종료와 안티 크롤링 환경의 모니터링',
    roleLabel: '02 · ROLE & SCOPE',
    roleTitle: '1인 풀스택 아키텍처 및 파이프라인 구축',
    processLabel: '03 · PROCESS',
    processTitle: '프로토타입부터 컨테이너 오케스트레이션까지',
    decisionsLabel: '04 · TECHNICAL DECISIONS',
    decisionsTitle: '안정적인 데이터 수집을 위한 핵심 기술 의사결정',
    troubleshootingLabel: '05 · TROUBLESHOOTING',
    troubleshootingTitle: '환경변수 이스케이프 및 봇 차단 대응',
    buildLabel: '06 · BUILD',
    buildTitle: '주요 구현',
    validationLabel: '07 · VALIDATION',
    validationTitle: '검증 기록과 운영 한계',
    outcomeLabel: '08 · RESULTS & RETROSPECTIVE',
    outcomeTitle: '프로젝트 성과와 배운 점',
  },
};

export const pricepulseEn = {
  ...shared,
  status: 'PERSONAL PROJECT · LOCAL DOCKER VERIFIED',
  coverAlt: 'PricePulse price monitoring dashboard interface',
  caseStudyLabel: 'View case study',
  gallery: {
    tagline: 'SmartStore price monitoring and anomaly detection',
    summary: 'Implemented collection, price-history, and alert paths. Login redirects on the validation network prevented an end-to-end check of live product collection and Slack delivery.',
    image: shared.cover,
    alt: 'PricePulse price monitoring dashboard',
    caption: 'Operations dashboard · Monitored item catalog and collection status',
    position: 'top',
  },
  summary: 'A personal project for observing price and stock changes on Naver SmartStore. I connected a Playwright collector, FastAPI, PostgreSQL history, n8n alert flow, and Next.js dashboard through Docker Compose. Live collection and Slack delivery remain unverified end to end due to network access restrictions.',
  problem: 'The seller-only Commerce API cannot query other stores, so the project uses public product pages. Login redirects and blocking can prevent a valid observation; failures must not be recorded as successful price measurements.',
  role: {
    summary: 'Owned the entire lifecycle from Turborepo monorepo architecture and Playwright crawler engine to asynchronous APIs, n8n alerting workflows, and Docker Compose infrastructure.',
    items: [
      'Turborepo monorepo architecture (Next.js web dashboard, FastAPI backend, n8n workflows, Compose infra)',
      'Playwright Chromium browser pool management and structured JSON-LD / __NEXT_DATA__ parsing engine',
      'FastAPI asynchronous REST API server, SQLAlchemy 2.0 ORM modeling (9 tables), internal protected endpoints',
      'Argon2id password hashing, SHA-256 session/CSRF token hashing, IP-based rate limiting security scheme',
      'n8n scheduled run trigger, Slack webhook dispatcher, and MinIO error artifact storage integration',
    ],
  },
  screenshots: [
    {
      src: '/pricepulse/dashboard.webp',
      alt: 'PricePulse monitoring dashboard screen',
      caption: 'Actual local demo · Item catalog, collection health, and price change metrics',
      width: 1440,
      height: 900,
    },
    {
      src: '/pricepulse/product-detail.webp',
      alt: 'Product detail and price history chart screen',
      caption: 'Actual local demo · SVG price trend chart and collection history per item',
      width: 1440,
      height: 900,
    },
    {
      src: '/pricepulse/admin-login.webp',
      alt: 'Admin session login screen',
      caption: 'Actual local demo · Argon2id and HttpOnly cookie administrator authentication',
      width: 1440,
      height: 900,
    },
  ],
  process: [
    {
      step: '01',
      title: 'Prototype',
      description: 'Analyzed the store limitation in the official Naver Commerce API and formalized ADR-0002 to pivot toward Playwright headless Chromium scraping. Verified a minimal crawler prototype that extracted price and stock status from target product URLs.',
      outputs: ['ADR-0002 record', 'Playwright proof of concept', 'Initial parser script'],
    },
    {
      step: '02',
      title: 'Plan',
      description: 'Designed a structured extraction strategy prioritizing schema.org JSON-LD metadata and SSR state objects (__NEXT_DATA__) over fragile DOM CSS selectors. Established a decoupled data model separating collection loops from alerting workflows.',
      outputs: ['Structured parsing spec', '9-table database schema', 'Decoupled alert model'],
    },
    {
      step: '03',
      title: 'Autopilot',
      description: 'Implemented FastAPI asynchronous endpoints and SQLAlchemy 2.0 ORM models, connecting n8n scheduled triggers. Applied randomized request jitters and stateless browser contexts, automating error escalation to NAVER_AUTH_FAILED upon login redirects.',
      outputs: ['FastAPI backend', 'n8n workflow pipelines', 'Stealth crawler core'],
    },
    {
      step: '04',
      title: 'Review',
      description: 'The repository records 42 backend unit tests and 18 integration tests in a local Compose setup. Login redirects on the validation network prevented completing live product parsing and Slack delivery.',
      outputs: ['60 unit and integration tests', 'Bot-detection verification', 'Production boundary analysis'],
    },
  ],
  decisions: [
    {
      title: 'ADR-0002: Headless Browser Scraping over Official API',
      context: 'The official Naver Commerce API only permits monitoring one own registered store, and the public shopping search API was deprecated.',
      decision: 'Built a Playwright collector instead of using the seller-only API, and classified blocked responses as failures.',
      impact: 'Collection can be attempted where public product pages are accessible; success on blocked networks is not established.',
    },
    {
      title: 'Prioritizing JSON-LD and __NEXT_DATA__ Hydration Payloads',
      context: 'E-commerce frontend DOM trees and CSS classes change frequently, causing high maintenance overhead for CSS-selector crawlers.',
      decision: 'The implemented parser tries JSON-LD and then __NEXT_DATA__. The DOM fallback is not implemented.',
      impact: 'Pages without structured data cannot be parsed; resilience to changes on the live site needs further validation.',
    },
    {
      title: 'Decoupling Crawling and Slack Alerting via Asynchronous Queue',
      context: 'Synchronously calling external Slack webhooks inside crawler loops risks blocking database transactions during network timeouts.',
      decision: 'FastAPI writes price change events to an append-only alert_events table, while n8n asynchronously polls, claims, and delivers notifications.',
      impact: 'External notification latency or outages cannot interrupt crawler data ingestion pipelines.',
    },
  ],
  troubleshooting: [
    {
      title: 'Argon2id Hash Dollar Sign Corruption in Docker Compose',
      problem: 'Admin login permanently failed when initializing accounts because Argon2id hashes ($argon2id$v=19$...) were corrupted during Compose variable substitution.',
      cause: 'Docker Compose treats unescaped dollar signs as environment variable substitution syntax, stripping or mangling the hash value.',
      solution: 'Escaped all dollar signs as $$argon2id$$... in compose.yaml and .env.example templates to preserve hash integrity.',
    },
    {
      title: 'Root Working Directory Environment Variable Mismatch',
      problem: 'Running Docker Compose from the repository root failed to load variables from infra/.env, causing database connection failures.',
      cause: 'Executing compose commands from the root resolves relative .env paths against the compose file directory rather than the execution root.',
      solution: 'Added explicit --env-file .env arguments to root package.json scripts to ensure consistent configuration injection across all environments.',
    },
    {
      title: 'Naver Bot Detection Classification and State Mapping',
      problem: 'When Naver detected automated requests and redirected to nid.naver.com, the crawler treated it as a generic HTML parse error, triggering useless retries.',
      cause: 'The parser lacked URL destination inspection, confusing an authentication redirect with an invalid page structure.',
      solution: 'Added final URL inspection to immediately raise a non-retryable NAVER_AUTH_FAILED exception and log an explicit bot-detection event.',
    },
  ],
  highlights: [
    'Next.js 16 web dashboard and FastAPI async API structured in a Turborepo monorepo',
    'Playwright Chromium crawler with structured JSON-LD and __NEXT_DATA__ extraction pipelines',
    'Internal token-protected endpoints (/internal/v1/*) integrated with n8n workflow triggers',
    'PostgreSQL 16 asynchronous ORM models across 9 tables managed by Alembic migrations',
    'Argon2id password hashing, HttpOnly sessions, and SHA-256 CSRF protection mechanisms',
  ],
  validation: [
    'Verified under local Docker Compose stack with 42 backend unit tests and 18 integration tests passing',
    'In local testing, live Naver store scraping and real Slack dispatch E2E were blocked by Naver login redirects; block-detection path verified',
    'The 3-stage parsing pipeline currently implements JSON-LD and __NEXT_DATA__ extraction; DOM fallback remains unimplemented',
    'Operates as a verified local Docker Compose template; no public live domain is deployed',
  ],
  outcome: {
    summary: 'Built a local monitoring flow separating price history from alert dispatch. Live product collection and Slack delivery remain unverified on the validation network.',
    results: [
      'Recorded local Compose orchestration of web, API, n8n, MinIO, PostgreSQL, and Caddy services; Playwright runs in the crawler process',
      'Recorded coverage of 42 backend unit tests and 18 integration tests',
      'Automated instant classification of Naver login redirects to eliminate runaway retry loops',
    ],
    learnings: [
      'A collector implementation does not guarantee access to an external site; network restrictions and usage conditions need separate checks.',
      'Pages without structured data need another parsing strategy and verification.',
      'Separating stored price changes from notification dispatch keeps their responsibilities distinct.',
    ],
  },
  detail: {
    backLabel: 'Portfolio',
    repositoryLabel: 'GitHub',
    eyebrow: 'PERSONAL PROJECT · AUTOMATION & CRAWLER',
    problemLabel: '01 · PROBLEM',
    problemTitle: 'Monitoring Under Discontinued APIs and Anti-Bot Barriers',
    roleLabel: '02 · ROLE & SCOPE',
    roleTitle: 'Full-Stack Architecture & Pipeline Implementation',
    processLabel: '03 · PROCESS',
    processTitle: 'From Prototype to Container Orchestration',
    decisionsLabel: '04 · TECHNICAL DECISIONS',
    decisionsTitle: 'Key Engineering Decisions for Reliable Ingestion',
    troubleshootingLabel: '05 · TROUBLESHOOTING',
    troubleshootingTitle: 'Environment Variable Escaping and Bot Redirects',
    buildLabel: '06 · BUILD',
    buildTitle: 'Key Implementation',
    validationLabel: '07 · VALIDATION',
    validationTitle: 'Verification Evidence and Operational Boundaries',
    outcomeLabel: '08 · RESULTS & RETROSPECTIVE',
    outcomeTitle: 'Project Outcomes and Retrospective',
  },
};
