const shared = {
  title: '자취방 수리 접수 플랫폼',
  slug: 'room-repair',
  published: false,
  repositoryUrl: 'https://github.com/lulupang2/room_repair_platform',
  cover: '/room-repair/architecture.svg',
  coverPosition: 'top',
  category: '08 · MOBILE & WEB · BAAS & RLS',
  cardBadge: 'SECURITY & IDEMPOTENCY',
  stack: ['Flutter', 'Dart', 'React 19', 'TypeScript', 'Supabase', 'PostgreSQL', 'Riverpod', 'Drift'],
};

export const roomRepairKo = {
  ...shared,
  status: '학습·포트폴리오 프로젝트 · 로컬 BaaS 검증',
  coverAlt: '자취방 수리 접수 플랫폼 시스템 및 보안 아키텍처 다이어그램',
  caseStudyLabel: '제작 과정과 상세 보기',
  gallery: {
    tagline: '원룸 설비 고장 접수부터 완료 보고서까지',
    summary: 'Flutter 고객 앱과 React 담당자 웹을 로컬 Supabase에 연결하고, RLS 권한 격리·멱등 요청·사진을 포함한 계정 삭제 절차를 구현했습니다.',
    image: shared.cover,
    alt: '자취방 수리 접수 플랫폼 아키텍처 다이어그램',
    caption: '시스템 아키텍처 도면 · Flutter 앱, React 관리자 웹, Supabase 백엔드',
    position: 'top',
  },
  summary: '원룸·자취방에서 발생하는 설비 고장을 세입자가 사진과 함께 접수하고, 운영진이 전용 웹 콘솔에서 상태를 전이하며 상담하는 모바일·웹 수리 플랫폼입니다. Flutter 앱, React 19 콘솔, Supabase BaaS(PostgreSQL RLS, RPC, Storage, Realtime, Edge Functions)를 결합하여 권한 격리와 데이터 정합성을 검증했습니다.',
  problem: '단순히 클라이언트 화면에서 버튼을 숨기는 방식은 비공개 스토리지나 API 직접 호출을 통한 권한 상승과 개인정보 노출을 막지 못합니다. 또한 모바일 환경의 불안정한 네트워크로 인한 중복 접수, 웹소켓 패킷 누락 시 상태 왜곡, 계정 탈퇴 시 스토리지에 사진이 방치되는 고아 데이터 문제가 발생합니다.',
  role: {
    summary: '모바일 클라이언트, 관리자 웹 콘솔, 데이터베이스 보안 정책, 서버리스 함수, 릴리스 검증 체계 전 과정을 1인 개발로 수행했습니다.',
    items: [
      'Flutter 기반 모바일 앱 아키텍처 구축 (Riverpod 상태 관리, Drift 로컬 DB 초안 자동 저장, Kakao 주소 WebView 브리지)',
      'React 19 + TypeScript 기반 운영 담당자 웹 콘솔 구현 (접수 목록, 상태 머신 제어, 실시간 상담 채팅)',
      'PostgreSQL 마이그레이션(10개), RLS 정책, SECURITY DEFINER RPC 3종 및 비공개 Storage 보안 체계 설계',
      'Deno 기반 Supabase Edge Functions 2종 구현 (원자적 계정 탈퇴 함수 delete-account, FCM 푸시 알림 발송)',
      'pgTAP 기반 112개 SQL 단위/통합 테스트 스위트 작성 및 Android 릴리스 서명 검사기(verify-android-signing) 구축',
    ],
  },
  screenshots: [
    {
      src: '/room-repair/architecture.svg',
      alt: '자취방 수리 접수 플랫폼 시스템 및 보안 아키텍처 다이어그램',
      caption: '설계 다이어그램 (소스코드 기반 아키텍처 도면, UI 캡처 아님) · Flutter 모바일, React 관리자 웹, Supabase RLS & Edge Functions',
      width: 1200,
      height: 800,
    },
    {
      src: '/room-repair/repair-lifecycle.svg',
      alt: '수리 접수 생명주기 및 상태 머신 다이어그램',
      caption: '생명주기 다이어그램 (UI 캡처 아님) · 로컬 초안 디바운스, 스토리지 가드 RPC, 실시간 상태 전이, PDF 보고서, 계정 탈퇴 흐름',
      width: 1200,
      height: 800,
    },
  ],
  process: [
    {
      step: '01',
      title: 'Prototype',
      description: '로컬 Docker 환경에 Supabase CLI 샌드박스를 구성하고 기본 헬스체크 RPC를 연결했습니다. 세입자 회원가입 시 DB 트리거로 customer 역할을 자동 부여하고 RLS로 타인 프로필 조회를 차단하는 최소 인증 프로토타입을 수립했습니다.',
      outputs: ['Docker Supabase 환경', '기본 RLS 프로필 정책', '인증 프로토타입'],
    },
    {
      step: '02',
      title: 'Plan',
      description: '비공개 버킷과 UUID 경로 격리를 적용하고, 스토리지 객체 소유권을 검증하는 원자적 create_repair_request RPC를 설계했습니다. 접수 건과 상담 메시지에 클라이언트 UUID 멱등키를 부여하여 중복 제출을 차단하는 데이터 계약을 수립했습니다.',
      outputs: ['스토리지 보안 정책', '멱등 RPC 명세', '상태 머신 계약'],
    },
    {
      step: '03',
      title: 'Autopilot',
      description: 'Flutter 앱에 Drift SQLite를 연동하여 작성 중 초안을 디바운스로 자동 저장하고, React 콘솔에는 단방향 상태 전이(received → in_progress → completed)를 구현했습니다. Realtime 웹소켓 신호를 수신하면 REST로 최신 상태를 재조회하도록 자동화했습니다.',
      outputs: ['Drift 로컬 자동저장', 'React 관리자 콘솔', '실시간 동기화 파이프라인'],
    },
    {
      step: '04',
      title: 'Review',
      description: '112개 pgTAP SQL 테스트와 Flutter/React 단위 테스트를 실행하여 전 구간을 검증했습니다. 탈퇴 시 Service Role을 통해 비공개 스토리지를 먼저 비우고 Auth 사용자를 삭제하는 delete-account 함수를 구현하여 고아 데이터 유실을 방지했습니다.',
      outputs: ['pgTAP 검증 기록', '계정 삭제 함수', '릴리스 서명 사전 검사'],
    },
  ],
  decisions: [
    {
      title: 'DB 기반 RLS & SECURITY DEFINER RPC 강제',
      context: '프론트엔드에서 UI 요소를 숨기는 방식은 API 직접 호출을 통한 권한 상승이나 데이터 오염을 방어할 수 없습니다.',
      decision: 'UI 제어를 배제하고 모든 데이터 접근과 상태 변경을 PostgreSQL RLS 정책과 SECURITY DEFINER RPC로 강제했습니다.',
      impact: '클라이언트 요청의 권한과 데이터 제약을 데이터베이스 계층에서 검증하도록 했습니다.',
    },
    {
      title: '클라이언트 UUID 기반 멱등 요청(Idempotency) 계약',
      context: '모바일 네트워크 단절 시 사용자가 제출 버튼을 여러 번 누르거나 자동 재시도가 발생해 중복 접수가 생성될 위험이 있습니다.',
      decision: '접수 생성 시 (customer_id, client_request_id), 상담 메시지에 client_message_id 고유 제약을 부여하고 RPC 내에서 중복 시 기존 레코드를 반환하도록 했습니다.',
      impact: '네트워크 재시도 시 중복 요청을 처리할 수 있도록 RPC 멱등성 계약을 적용했습니다.',
    },
    {
      title: 'Realtime 이벤트의 인벌리데이션 시그널(Invalidation) 활용',
      context: '웹소켓 이벤트 페이로드에 의존해 클라이언트 상태를 직접 누적할 경우, 패킷 유실이나 순서 역전 시 정합성이 깨집니다.',
      decision: '웹소켓 페이로드를 UI 상태로 직접 머지하지 않고 변경을 알리는 트리거 신호로만 사용하며, 클라이언트는 권한이 적용된 최신 REST 조회를 다시 수행하도록 설계했습니다.',
      impact: '클라이언트가 알림 페이로드를 누적하지 않고 서버 상태를 다시 조회하도록 했습니다.',
    },
    {
      title: '핵심 트랜잭션과 푸시 알림의 격리 (Fail-open)',
      context: '접수 상태 전이나 상담 저장 시 외부 FCM 푸시 발송 실패가 비즈니스 트랜잭션을 롤백시킬 위험이 있습니다.',
      decision: 'DB 트랜잭션은 성공적으로 커밋하고, 푸시 알림 발송은 Best-effort(Fail-open) 방식으로 격리했습니다.',
      impact: '외부 알림 인프라의 일시적 장애가 핵심 접수 업무를 블로킹하지 않도록 보호했습니다.',
    },
  ],
  troubleshooting: [
    {
      title: '스토리지 사진 업로드와 DB 접수 생성 사이의 정합성 불일치',
      problem: '사진 파일 업로드 성공 후 네트워크 단절로 DB RPC 호출이 실패할 경우, 비공개 스토리지에 고아 파일이 남거나 중복 재시도 시 데이터가 왜곡됨.',
      cause: '파일 스토리지 업로드와 DB 저장이 서로 다른 물리 트랜잭션으로 분리되어 있어 원자성이 깨짐.',
      solution: 'RPC 내부에서 전달받은 스토리지 경로의 실제 존재 여부와 호출자 소유권을 확인하는 guard 함수를 추가하고, 클라이언트 재시도 시 동일한 client_request_id와 업로드 사진 목록을 재사용하도록 멱등 흐름을 정립함.',
    },
    {
      title: '모바일 화면 dispose 시 Riverpod ref 접근 예외 발생',
      problem: '화면 이탈 시점에 작성 중이던 폼 초안을 Drift DB에 자동 저장하려 할 때 위젯 트리 해제로 인해 ref 접근 StateError가 발생함.',
      cause: 'StatefulWidget의 dispose 라이프사이클 단계에서는 이미 위젯 트리에서 분리되어 Riverpod ref 조회가 안전하지 않음.',
      solution: 'initState 시점에 로컬 저장소와 사용자 ID 참조를 로컬 변수에 캐싱해 두고, dispose 시점의 스냅샷은 ref 의존성 없이 안전하게 비동기 저장하도록 분리함.',
    },
    {
      title: '회원 탈퇴 시 비공개 스토리지 파일 잔류 및 권한 거부',
      problem: '고객 탈퇴 시 Auth 사용자가 먼저 삭제되면 RLS 정책에 의해 스토리지 파일 삭제 권한이 상실되어 사진 파일이 스토리지에 영구 잔류함.',
      cause: '클라이언트 세션 토큰으로 탈퇴를 실행할 경우 본인 계정이 삭제된 직후 스토리지 삭제 API 호출 권한이 사라짐.',
      solution: 'Service Role 권한을 갖는 delete-account Edge Function을 구축하여, 호출자 세션을 먼저 검증한 뒤 고객 전용 스토리지 폴더 내 사진을 우선 삭제하고 Auth 사용자를 삭제하도록 순서를 강제함 (FK cascade로 DB 데이터 자동 정리).',
    },
  ],
  highlights: [
    'Flutter 모바일 앱과 React 19 관리자 웹을 아우르는 풀스택 수리 접수 플랫폼',
    'PostgreSQL RLS 정책 및 SECURITY DEFINER RPC 기반 권한 격리와 멱등 트랜잭션 구현',
    'Drift SQLite 기반 디바운스 초안 자동 저장 및 오프라인 최근 조회 캐시 지원',
    'Noto Sans KR 폰트 및 고장 사진을 임베드한 완료 보고서 PDF 네이티브 생성',
    'Service Role 기반 고객 탈퇴 Edge Function 구축으로 스토리지 정리 절차 구현',
  ],
  validation: [
    '로컬 Supabase 환경에서 pgTAP SQL 테스트 스위트 7개 파일 / 112개 전원 통과',
    'Flutter analyze 결과 0 issues 및 단위/위젯/리포트 테스트 21개 전원 통과',
    'React 19 관리자 웹 oxlint 0 warnings / 0 errors 및 단위 테스트 10개 통과',
    'Stage 7 검증기를 통한 고객 탈퇴 시 스토리지 파일 및 DB 완전 삭제 무결성 입증',
    '상용 Supabase 클라우드 호스팅 및 앱스토어 배포는 외부 운영 영역으로 로컬 Docker 검증 완료',
  ],
  outcome: {
    summary: 'UI 레벨 통제를 넘어 데이터베이스 단에서 권한과 멱등성을 적용하고, 계정 탈퇴 생명주기의 데이터 정리 절차를 구현했습니다.',
    results: [
      'pgTAP DB 테스트 112개 및 클라이언트 테스트 31개 전원 통과를 통한 무결성 입증',
      'Flutter 앱과 React 웹 콘솔 간 Supabase Realtime 기반 단일 진실 공급원(SSOT) 동기화 확보',
      '계정 탈퇴 시 Storage 파일을 먼저 삭제하고 Auth 사용자를 제거하는 파이프라인을 로컬 검증',
    ],
    learnings: [
      '신뢰 경계는 프론트엔드가 아닌 데이터베이스의 RLS와 RPC 단에서 완결되어야 함을 체득',
      '네트워크 장애가 잦은 모바일 환경에서 멱등키와 인벌리데이션 시그널의 결합이 데이터 왜곡을 방지하는 최적의 패턴임을 학습',
      '외부 푸시나 서드파티 서비스 장애가 핵심 비즈니스 저장을 훼손하지 않도록 Fail-open 분리의 중요성 확인',
    ],
  },
  detail: {
    backLabel: 'Portfolio',
    repositoryLabel: 'GitHub',
    eyebrow: 'PERSONAL PROJECT · MOBILE & BAAS',
    problemLabel: '01 · PROBLEM',
    problemTitle: 'UI 중심 통제의 한계와 데이터 불일치 위험',
    roleLabel: '02 · ROLE & SCOPE',
    roleTitle: '모바일·웹·BaaS 풀스택 1인 설계 및 구현',
    processLabel: '03 · PROCESS',
    processTitle: '기반 구축부터 배포 사전 검증까지',
    decisionsLabel: '04 · TECHNICAL DECISIONS',
    decisionsTitle: '안전한 운영을 위한 핵심 아키텍처 의사결정',
    troubleshootingLabel: '05 · TROUBLESHOOTING',
    troubleshootingTitle: '스토리지 가드 및 계정 탈퇴 무결성 확보',
    buildLabel: '06 · BUILD',
    buildTitle: '주요 구현',
    validationLabel: '07 · VALIDATION',
    validationTitle: '검증 기록과 시스템 경계',
    outcomeLabel: '08 · RESULTS & RETROSPECTIVE',
    outcomeTitle: '프로젝트 성과와 배운 점',
  },
};

export const roomRepairEn = {
  ...shared,
  title: 'Room Repair Platform',
  status: 'PERSONAL PROJECT · LOCAL BAAS VERIFIED',
  coverAlt: 'Room Repair Platform system and security architecture diagram',
  caseStudyLabel: 'View case study',
  gallery: {
    tagline: 'From facility repair requests to completion reports',
    summary: 'Integrated a Flutter tenant mobile app and a React staff web console with Supabase BaaS, enforcing RLS authorization, idempotency, and atomic account deletion.',
    image: shared.cover,
    alt: 'Room Repair Platform architecture diagram',
    caption: 'System architecture diagram · Flutter mobile app, React staff web console, Supabase backend',
    position: 'top',
  },
  summary: 'A mobile and web facility repair platform enabling studio apartment tenants to submit malfunction tickets with photos, while operations staff manage lifecycle states and conduct consultations. Built with Flutter, React 19, and Supabase BaaS (PostgreSQL RLS, RPCs, Storage, Realtime, and Edge Functions).',
  problem: 'Hiding UI controls on client devices does not prevent malicious actors from directly invoking private APIs or storage buckets, risking unauthorized role escalation and personal data leakage. In addition, unstable mobile connections lead to duplicate submissions, WebSocket drops corrupt client state, and account deletion frequently leaves orphaned photo files in private storage.',
  role: {
    summary: 'Owned the end-to-end design and implementation spanning mobile clients, staff web consoles, database security policies, serverless functions, and release verification pipelines.',
    items: [
      'Architected Flutter mobile app (Riverpod state management, Drift SQLite draft debouncing, Kakao Address WebView bridge)',
      'Built React 19 + TypeScript staff console (ticket filtering, state machine transitions, realtime messaging)',
      'Engineered PostgreSQL schema (10 migrations), RLS policies, 3 SECURITY DEFINER RPCs, and private storage rules',
      'Developed Supabase Edge Functions (atomic account deletion delete-account and FCM notification dispatcher)',
      'Authored 112 pgTAP SQL tests and built an automated Android release signing validator (verify-android-signing)',
    ],
  },
  screenshots: [
    {
      src: '/room-repair/architecture.svg',
      alt: 'Room Repair Platform system and security architecture diagram',
      caption: 'System architecture diagram (source-backed diagram, not a live UI screenshot) · Flutter mobile, React staff web, Supabase RLS & Edge Functions',
      width: 1200,
      height: 800,
    },
    {
      src: '/room-repair/repair-lifecycle.svg',
      alt: 'Repair request lifecycle and state machine diagram',
      caption: 'Lifecycle diagram (not a live UI screenshot) · Local draft debouncing, storage photo guard RPC, state transitions, PDF reporting, and account deletion',
      width: 1200,
      height: 800,
    },
  ],
  process: [
    {
      step: '01',
      title: 'Prototype',
      description: 'Configured a local Docker Supabase CLI sandbox and wired baseline health-check RPCs. Implemented database triggers assigning the customer role upon registration and enforced RLS policies preventing unauthorized profile reads.',
      outputs: ['Docker Supabase sandbox', 'Baseline RLS policies', 'Authentication prototype'],
    },
    {
      step: '02',
      title: 'Plan',
      description: 'Implemented private storage buckets with tenant UUID path partitioning and authored an atomic create_repair_request RPC verifying file ownership. Established client request UUID idempotency keys to prevent duplicate submissions.',
      outputs: ['Storage security policies', 'Idempotent RPC spec', 'State machine contract'],
    },
    {
      step: '03',
      title: 'Autopilot',
      description: 'Integrated Drift SQLite into Flutter to debounce and auto-save form drafts, while building a forward state machine (received to in_progress to completed) in the React console. Configured Realtime invalidation triggers prompting authoritative REST re-fetches.',
      outputs: ['Drift local auto-save', 'React staff console', 'Realtime synchronization'],
    },
    {
      step: '04',
      title: 'Review',
      description: 'Executed 112 pgTAP SQL tests alongside Flutter and React test suites. Implemented the delete-account Edge Function using Service Role privileges to delete private storage photos before user deletion, then checked the flow in the local verifier.',
      outputs: ['112 pgTAP tests passing', 'Atomic deletion function', 'Release signing verifier'],
    },
  ],
  decisions: [
    {
      title: 'Enforcing Database-Level RLS and SECURITY DEFINER RPCs',
      context: 'Relying on frontend UI controls to hide elements fails to stop direct API requests from forging parameters or exfiltrating data.',
      decision: 'Rejected UI-only hiding and mandated that all data mutations and state transitions execute through PostgreSQL RLS policies and SECURITY DEFINER RPCs.',
      impact: 'Enforced authorization and data constraints in the database layer rather than relying on UI controls.',
    },
    {
      title: 'Client Request UUID-Based Idempotency Contracts',
      context: 'Unstable mobile connectivity leads users to tap submit repeatedly, creating duplicate repair tickets and messages.',
      decision: 'Imposed unique constraints on (customer_id, client_request_id) and client_message_id, returning existing rows on retry inside RPCs.',
      impact: 'Added idempotent handling for duplicate repair and chat requests across intermittent network retries.',
    },
    {
      title: 'Using Realtime Events Exclusively as Invalidation Signals',
      context: 'Directly mutating client UI state from incoming WebSocket payloads risks data corruption when packets arrive out of order or drop.',
      decision: 'Treated WebSocket events solely as invalidation triggers, prompting the client to re-fetch authoritative data via authenticated REST endpoints.',
      impact: 'Clients re-fetch authoritative server state after invalidation events to reduce stale-state risk.',
    },
    {
      title: 'Decoupling Push Notifications from Business Transactions',
      context: 'Failures during external FCM push dispatch could roll back valid repair status transitions and message writes.',
      decision: 'Committed core database records first and handled FCM push dispatch in a fail-open, best-effort manner.',
      impact: 'Prevented third-party notification delays or outages from interrupting core repair workflows.',
    },
  ],
  troubleshooting: [
    {
      title: 'Inconsistency between Storage Photo Upload and DB Creation',
      problem: 'When a network drop occurred after photo upload but before the DB RPC call, orphaned files remained in storage or corrupted retries.',
      cause: 'File storage uploads and database transactions occurred across separate physical channels without unified atomicity.',
      solution: 'Added an internal storage guard to the create_repair_request RPC verifying file existence and caller ownership, while standardizing idempotent client UUID retries reusing already-uploaded paths.',
    },
    {
      title: 'Riverpod ref Access Exception during Widget Disposal',
      problem: 'Attempting to auto-save draft form states to Drift DB during widget disposal triggered StateError exceptions due to unmounted ref access.',
      cause: 'StatefulWidget dispose callbacks run after the element tree decouples from Riverpod provider containers.',
      solution: 'Cached database store instances and user IDs during initState into local widget variables, allowing dispose logic to save snapshots without referencing ref.',
    },
    {
      title: 'Orphaned Private Storage Files during User Account Deletion',
      problem: 'Deleting auth users directly revoked storage deletion permissions under RLS, permanently stranding private photos in storage buckets.',
      cause: 'Client-authenticated JWT sessions lose access rights the instant the corresponding Auth user is purged.',
      solution: 'Created a delete-account Edge Function with Service Role privileges that validates caller tokens, deletes private storage photos first, and then deletes the Auth user (triggering database cascading deletes).',
    },
  ],
  highlights: [
    'Full-stack repair platform spanning a Flutter mobile client and React 19 operations web console',
    'PostgreSQL RLS policies and SECURITY DEFINER RPCs enforcing authorization and idempotent transactions',
    'Drift SQLite local engine for form debouncing, draft preservation, and offline cache fallbacks',
    'Native PDF completion report generator embedding Noto Sans KR fonts and verified inspection photos',
    'Service Role-driven customer deletion Edge Function with ordered storage cleanup',
  ],
  validation: [
    '112 pgTAP SQL tests passing across 7 test suites in the local Supabase environment',
    'Flutter analyze passing with 0 issues and 21 unit, widget, and report tests passing',
    'React 19 operations web console passing with 0 oxlint warnings/errors and 10 unit tests passing',
    'Stage 7 verifier tested storage-file removal and database cleanup in the account-deletion scenario',
    'Verified under local Docker Supabase CLI sandbox; hosted Supabase and store releases are external operations',
  ],
  outcome: {
    summary: 'Delivered a repair platform prototype with database-enforced authorization and account lifecycle cleanup.',
    results: [
      'Recorded passing results across 112 database tests and 31 frontend client tests',
      'Established single-source-of-truth synchronization between Flutter and React using Supabase Realtime',
      'Verified storage-file deletion before Auth user removal in the local account-deletion scenario',
    ],
    learnings: [
      'Realized that security trust boundaries must terminate at the database layer (RLS and RPCs) rather than UI logic',
      'Mastered combining client idempotency keys with invalidation signals to eliminate mobile data drift',
      'Confirmed the importance of fail-open isolation for third-party notification services to safeguard core transactions',
    ],
  },
  detail: {
    backLabel: 'Portfolio',
    repositoryLabel: 'GitHub',
    eyebrow: 'PERSONAL PROJECT · MOBILE & BAAS',
    problemLabel: '01 · PROBLEM',
    problemTitle: 'Limits of UI-Level Controls and Data Inconsistency Risks',
    roleLabel: '02 · ROLE & SCOPE',
    roleTitle: 'Full-Stack Architecture & Implementation Scope',
    processLabel: '03 · PROCESS',
    processTitle: 'From Foundation Setup to Pre-Deployment Verification',
    decisionsLabel: '04 · TECHNICAL DECISIONS',
    decisionsTitle: 'Key Architectural Decisions for Secure Operations',
    troubleshootingLabel: '05 · TROUBLESHOOTING',
    troubleshootingTitle: 'Storage Guards and Account Deletion Integrity',
    buildLabel: '06 · BUILD',
    buildTitle: 'Key Implementation',
    validationLabel: '07 · VALIDATION',
    validationTitle: 'Verification Evidence and System Boundaries',
    outcomeLabel: '08 · RESULTS & RETROSPECTIVE',
    outcomeTitle: 'Project Outcomes and Retrospective',
  },
};
